/**
 * @file dashboard.c
 * @brief Modern, responsive Swagger-like web dashboard implementation
 * @details Provides Swagger UI, ReDoc, and OpenAPI spec endpoints
 */

#include "crest/crest.h"
#include "crest/types.h"
#include "crest/openapi.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void crest_dashboard_handler(crest_request_t *req, crest_response_t *res) {
    crest_app_t *app = (crest_app_t*)req->user_data;
    
    const char *html = "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <meta name=\"description\" content=\"Interactive API documentation and testing dashboard for Crest Framework\">\n"
        "    <title>Crest API Dashboard - Interactive Documentation</title>\n"
        "    <style>\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        :root {\n"
        "            --primary: #667eea;\n"
        "            --primary-dark: #5568d3;\n"
        "            --secondary: #764ba2;\n"
        "            --success: #10b981;\n"
        "            --warning: #f59e0b;\n"
        "            --danger: #ef4444;\n"
        "            --info: #3b82f6;\n"
        "            --purple: #8b5cf6;\n"
        "            --gray-50: #f9fafb;\n"
        "            --gray-100: #f3f4f6;\n"
        "            --gray-200: #e5e7eb;\n"
        "            --gray-300: #d1d5db;\n"
        "            --gray-600: #4b5563;\n"
        "            --gray-700: #374151;\n"
        "            --gray-800: #1f2937;\n"
        "            --gray-900: #111827;\n"
        "            --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);\n"
        "            --shadow: 0 2px 4px rgba(0,0,0,0.1);\n"
        "            --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);\n"
        "            --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);\n"
        "        }\n"
        "        body { \n"
        "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; \n"
        "            background: var(--gray-50);\n"
        "            color: var(--gray-900);\n"
        "            line-height: 1.6;\n"
        "        }\n"
        "        .header { \n"
        "            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%); \n"
        "            color: white; \n"
        "            padding: 3rem 2rem; \n"
        "            text-align: center;\n"
        "            box-shadow: var(--shadow-lg);\n"
        "        }\n"
        "        .header h1 { font-size: clamp(1.75rem, 5vw, 2.5rem); margin-bottom: 0.5rem; font-weight: 700; }\n"
        "        .header p { opacity: 0.95; font-size: 1.125rem; }\n"
        "        .container { max-width: 1400px; margin: 2rem auto; padding: 0 1.5rem; }\n"
        "        .stats { \n"
        "            display: grid; \n"
        "            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); \n"
        "            gap: 1.5rem; \n"
        "            margin-bottom: 2.5rem; \n"
        "        }\n"
        "        .stat-card { \n"
        "            background: white; \n"
        "            border-radius: 12px; \n"
        "            padding: 2rem; \n"
        "            box-shadow: var(--shadow-md);\n"
        "            transition: transform 0.2s, box-shadow 0.2s;\n"
        "            border-left: 4px solid var(--primary);\n"
        "        }\n"
        "        .stat-card:hover { transform: translateY(-2px); box-shadow: var(--shadow-lg); }\n"
        "        .stat-value { font-size: 2.5rem; font-weight: 700; color: var(--primary); }\n"
        "        .stat-label { color: var(--gray-600); margin-top: 0.5rem; font-weight: 500; }\n"
        "        .section-title { \n"
        "            font-size: 1.75rem; \n"
        "            font-weight: 700; \n"
        "            color: var(--gray-800); \n"
        "            margin-bottom: 1.5rem;\n"
        "            display: flex;\n"
        "            align-items: center;\n"
        "            gap: 0.75rem;\n"
        "        }\n"
        "        .route-card { \n"
        "            background: white; \n"
        "            border-radius: 12px; \n"
        "            padding: 0; \n"
        "            margin-bottom: 1.5rem; \n"
        "            box-shadow: var(--shadow);\n"
        "            overflow: hidden;\n"
        "            border: 1px solid var(--gray-200);\n"
        "            transition: all 0.2s;\n"
        "        }\n"
        "        .route-card:hover { box-shadow: var(--shadow-md); transform: translateY(-1px); }\n"
        "        .route-header { \n"
        "            display: flex; \n"
        "            align-items: center; \n"
        "            gap: 1rem; \n"
        "            padding: 1.5rem;\n"
        "            cursor: pointer;\n"
        "            background: var(--gray-50);\n"
        "            border-bottom: 1px solid var(--gray-200);\n"
        "        }\n"
        "        .route-header:hover { background: white; }\n"
        "        .method { \n"
        "            padding: 0.4rem 1rem; \n"
        "            border-radius: 6px; \n"
        "            font-weight: 700; \n"
        "            font-size: 0.875rem;\n"
        "            text-transform: uppercase;\n"
        "            letter-spacing: 0.5px;\n"
        "            min-width: 85px;\n"
        "            text-align: center;\n"
        "            box-shadow: var(--shadow-sm);\n"
        "        }\n"
        "        .method-get { background: var(--success); color: white; }\n"
        "        .method-post { background: var(--info); color: white; }\n"
        "        .method-put { background: var(--warning); color: white; }\n"
        "        .method-delete { background: var(--danger); color: white; }\n"
        "        .method-patch { background: var(--purple); color: white; }\n"
        "        .method-head { background: var(--gray-600); color: white; }\n"
        "        .method-options { background: var(--gray-700); color: white; }\n"
        "        .path { \n"
        "            font-family: 'Courier New', 'Consolas', monospace; \n"
        "            font-size: 1.125rem; \n"
        "            font-weight: 600;\n"
        "            flex: 1;\n"
        "            color: var(--gray-800);\n"
        "        }\n"
        "        .expand-icon { \n"
        "            width: 24px; \n"
        "            height: 24px;\n"
        "            transition: transform 0.3s;\n"
        "            color: var(--gray-600);\n"
        "        }\n"
        "        .expand-icon.expanded { transform: rotate(180deg); }\n"
        "        .route-details { \n"
        "            display: none; \n"
        "            padding: 1.5rem;\n"
        "            background: white;\n"
        "        }\n"
        "        .route-details.show { display: block; animation: slideDown 0.3s ease; }\n"
        "        @keyframes slideDown { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }\n"
        "        .description { \n"
        "            color: var(--gray-600); \n"
        "            margin-bottom: 1.5rem;\n"
        "            padding: 1rem;\n"
        "            background: var(--gray-50);\n"
        "            border-radius: 8px;\n"
        "            border-left: 3px solid var(--primary);\n"
        "        }\n"
        "        .try-it-out { \n"
        "            margin-top: 1.5rem;\n"
        "            padding: 1.5rem;\n"
        "            background: var(--gray-50);\n"
        "            border-radius: 8px;\n"
        "        }\n"
        "        .try-it-out h4 { \n"
        "            color: var(--gray-800); \n"
        "            margin-bottom: 1rem;\n"
        "            font-size: 1.125rem;\n"
        "        }\n"
        "        .form-group { margin-bottom: 1rem; }\n"
        "        .form-group label { \n"
        "            display: block; \n"
        "            margin-bottom: 0.5rem;\n"
        "            color: var(--gray-700);\n"
        "            font-weight: 600;\n"
        "            font-size: 0.875rem;\n"
        "        }\n"
        "        .form-group input, .form-group textarea { \n"
        "            width: 100%; \n"
        "            padding: 0.75rem; \n"
        "            border: 2px solid var(--gray-200);\n"
        "            border-radius: 6px;\n"
        "            font-family: 'Courier New', monospace;\n"
        "            font-size: 0.875rem;\n"
        "            transition: border-color 0.2s;\n"
        "        }\n"
        "        .form-group input:focus, .form-group textarea:focus { \n"
        "            outline: none; \n"
        "            border-color: var(--primary);\n"
        "            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n"
        "        }\n"
        "        .btn { \n"
        "            padding: 0.75rem 1.5rem; \n"
        "            background: var(--primary); \n"
        "            color: white; \n"
        "            border: none; \n"
        "            border-radius: 6px; \n"
        "            cursor: pointer;\n"
        "            font-weight: 600;\n"
        "            font-size: 1rem;\n"
        "            transition: all 0.2s;\n"
        "            box-shadow: var(--shadow-sm);\n"
        "        }\n"
        "        .btn:hover { background: var(--primary-dark); box-shadow: var(--shadow-md); transform: translateY(-1px); }\n"
        "        .btn:active { transform: translateY(0); }\n"
        "        .response-area { \n"
        "            margin-top: 1.5rem;\n"
        "            padding: 1.5rem;\n"
        "            background: var(--gray-900);\n"
        "            color: #10b981;\n"
        "            border-radius: 8px;\n"
        "            font-family: 'Courier New', monospace;\n"
        "            font-size: 0.875rem;\n"
        "            overflow-x: auto;\n"
        "            box-shadow: var(--shadow-md);\n"
        "            white-space: pre-wrap;\n"
        "            word-wrap: break-word;\n"
        "        }\n"
        "        .response-area.error { color: #ef4444; }\n"
        "        .search-box { \n"
        "            margin-bottom: 2rem;\n"
        "            position: relative;\n"
        "        }\n"
        "        .search-box input { \n"
        "            width: 100%;\n"
        "            padding: 1rem 1rem 1rem 3rem;\n"
        "            border: 2px solid var(--gray-200);\n"
        "            border-radius: 12px;\n"
        "            font-size: 1rem;\n"
        "            transition: all 0.2s;\n"
        "            background: white;\n"
        "            box-shadow: var(--shadow-sm);\n"
        "        }\n"
        "        .search-box input:focus { \n"
        "            outline: none;\n"
        "            border-color: var(--primary);\n"
        "            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1), var(--shadow-md);\n"
        "        }\n"
        "        .search-icon { \n"
        "            position: absolute;\n"
        "            left: 1rem;\n"
        "            top: 50%;\n"
        "            transform: translateY(-50%);\n"
        "            color: var(--gray-600);\n"
        "        }\n"
        "        .footer { \n"
        "            text-align: center;\n"
        "            padding: 2rem;\n"
        "            color: var(--gray-600);\n"
        "            background: white;\n"
        "            margin-top: 3rem;\n"
        "            border-top: 1px solid var(--gray-200);\n"
        "        }\n"
        "        @media (max-width: 768px) {\n"
        "            .container { padding: 0 1rem; }\n"
        "            .header { padding: 2rem 1rem; }\n"
        "            .header h1 { font-size: 1.75rem; }\n"
        "            .stats { grid-template-columns: 1fr; gap: 1rem; }\n"
        "            .route-header { flex-wrap: wrap; }\n"
        "            .method { min-width: auto; }\n"
        "            .path { font-size: 1rem; word-break: break-all; }\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"header\">\n"
        "        <h1>🌊 Crest API Dashboard</h1>\n"
        "        <p>Interactive API Documentation & Testing</p>\n"
        "    </div>\n"
        "    <div class=\"container\">\n"
        "        <div class=\"stats\">\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-value\" id=\"total-routes\">0</div>\n"
        "                <div class=\"stat-label\">Total Endpoints</div>\n"
        "            </div>\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-value\">v" CREST_VERSION "</div>\n"
        "                <div class=\"stat-label\">Framework Version</div>\n"
        "            </div>\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-value\" id=\"method-count\">0</div>\n"
        "                <div class=\"stat-label\">HTTP Methods</div>\n"
        "            </div>\n"
        "        </div>\n"
        "        <div class=\"search-box\">\n"
        "            <svg class=\"search-icon\" width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n"
        "                <path fill-rule=\"evenodd\" d=\"M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z\" clip-rule=\"evenodd\"/>\n"
        "            </svg>\n"
        "            <input type=\"text\" id=\"search-input\" placeholder=\"Search endpoints by path or description...\" />\n"
        "        </div>\n"
        "        <h2 class=\"section-title\">\n"
        "            <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"currentColor\">\n"
        "                <path d=\"M7 6v12a2 2 0 002 2h6a2 2 0 002-2V6a2 2 0 00-2-2H9a2 2 0 00-2 2z\"/>\n"
        "            </svg>\n"
        "            API Endpoints\n"
        "        </h2>\n"
        "        <div id=\"routes-container\"></div>\n"
        "    </div>\n"
        "    <div class=\"footer\">\n"
        "        <p>Powered by <strong>Crest Framework v" CREST_VERSION "</strong> - High-performance C/C++ REST API Framework</p>\n"
        "        <p style=\"margin-top: 0.5rem; font-size: 0.875rem;\">Built with ❤️ for simplicity and speed</p>\n"
        "    </div>\n"
        "    <script>\n"
        "        let allRoutes = [];\n"
        "        \n"
        "        fetch('/api/routes')\n"
        "            .then(res => res.json())\n"
        "            .then(data => {\n"
        "                allRoutes = data.routes;\n"
        "                renderRoutes(allRoutes);\n"
        "                updateStats(allRoutes);\n"
        "            })\n"
        "            .catch(err => console.error('Failed to load routes:', err));\n"
        "        \n"
        "        function updateStats(routes) {\n"
        "            document.getElementById('total-routes').textContent = routes.length;\n"
        "            const uniqueMethods = new Set(routes.map(r => r.method));\n"
        "            document.getElementById('method-count').textContent = uniqueMethods.size;\n"
        "        }\n"
        "        \n"
        "        function renderRoutes(routes) {\n"
        "            const container = document.getElementById('routes-container');\n"
        "            container.innerHTML = '';\n"
        "            \n"
        "            if (routes.length === 0) {\n"
        "                container.innerHTML = '<p style=\"text-align: center; padding: 2rem; color: var(--gray-600);\">No routes found</p>';\n"
        "                return;\n"
        "            }\n"
        "            \n"
        "            routes.forEach((route, idx) => {\n"
        "                const methodClass = 'method-' + route.method.toLowerCase();\n"
        "                const card = document.createElement('div');\n"
        "                card.className = 'route-card';\n"
        "                const detailsId = 'details-' + idx;\n"
        "                const iconId = 'icon-' + idx;\n"
        "                \n"
        "                card.innerHTML = `\n"
        "                    <div class=\"route-header\" onclick=\"toggleDetails('${detailsId}', '${iconId}')\">\n"
        "                        <span class=\"method ${methodClass}\">${route.method}</span>\n"
        "                        <span class=\"path\">${route.path}</span>\n"
        "                        <svg id=\"${iconId}\" class=\"expand-icon\" fill=\"currentColor\" viewBox=\"0 0 20 20\">\n"
        "                            <path fill-rule=\"evenodd\" d=\"M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z\" clip-rule=\"evenodd\"/>\n"
        "                        </svg>\n"
        "                    </div>\n"
        "                    <div id=\"${detailsId}\" class=\"route-details\">\n"
        "                        ${route.description ? `<div class=\"description\"><strong>Description:</strong> ${route.description}</div>` : ''}\n"
        "                        <div class=\"try-it-out\">\n"
        "                            <h4>🧪 Try it out</h4>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Request URL</label>\n"
        "                                <input type=\"text\" value=\"${route.path}\" id=\"url-${idx}\" />\n"
        "                            </div>\n"
        "                            ${route.method === 'POST' || route.method === 'PUT' || route.method === 'PATCH' ? `\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Request Body (JSON)</label>\n"
        "                                <textarea rows=\"4\" id=\"body-${idx}\" placeholder='{\"key\": \"value\"}'></textarea>\n"
        "                            </div>` : ''}\n"
        "                            <button class=\"btn\" onclick=\"testRoute('${route.method}', ${idx})\">Execute</button>\n"
        "                            <div id=\"response-${idx}\"></div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                `;\n"
        "                container.appendChild(card);\n"
        "            });\n"
        "        }\n"
        "        \n"
        "        function toggleDetails(detailsId, iconId) {\n"
        "            const details = document.getElementById(detailsId);\n"
        "            const icon = document.getElementById(iconId);\n"
        "            details.classList.toggle('show');\n"
        "            icon.classList.toggle('expanded');\n"
        "        }\n"
        "        \n"
        "        async function testRoute(method, idx) {\n"
        "            const url = document.getElementById('url-' + idx).value;\n"
        "            const responseDiv = document.getElementById('response-' + idx);\n"
        "            \n"
        "            let options = { method: method };\n"
        "            \n"
        "            if (method === 'POST' || method === 'PUT' || method === 'PATCH') {\n"
        "                const bodyInput = document.getElementById('body-' + idx);\n"
        "                if (bodyInput && bodyInput.value) {\n"
        "                    options.body = bodyInput.value;\n"
        "                    options.headers = { 'Content-Type': 'application/json' };\n"
        "                }\n"
        "            }\n"
        "            \n"
        "            try {\n"
        "                const start = performance.now();\n"
        "                const response = await fetch(url, options);\n"
        "                const duration = (performance.now() - start).toFixed(2);\n"
        "                const contentType = response.headers.get('content-type');\n"
        "                let body;\n"
        "                \n"
        "                if (contentType && contentType.includes('application/json')) {\n"
        "                    body = JSON.stringify(await response.json(), null, 2);\n"
        "                } else {\n"
        "                    body = await response.text();\n"
        "                }\n"
        "                \n"
        "                responseDiv.innerHTML = `<div class=\"response-area\">\n"
        "Status: ${response.status} ${response.statusText}\n"
        "Time: ${duration}ms\n"
        "Content-Type: ${contentType}\n"
        "\n"
        "${body}</div>`;\n"
        "            } catch (error) {\n"
        "                responseDiv.innerHTML = `<div class=\"response-area error\">Error: ${error.message}</div>`;\n"
        "            }\n"
        "        }\n"
        "        \n"
        "        document.getElementById('search-input').addEventListener('input', (e) => {\n"
        "            const search = e.target.value.toLowerCase();\n"
        "            const filtered = allRoutes.filter(r => \n"
        "                r.path.toLowerCase().includes(search) || \n"
        "                (r.description && r.description.toLowerCase().includes(search)) ||\n"
        "                r.method.toLowerCase().includes(search)\n"
        "            );\n"
        "            renderRoutes(filtered);\n"
        "        });\n"
        "    </script>\n"
        "</body>\n"
        "</html>";
    
    crest_response_header(res, "Content-Type", "text/html; charset=utf-8");
    crest_response_send(res, html);
}

void crest_api_routes_handler(crest_request_t *req, crest_response_t *res) {
    crest_app_t *app = (crest_app_t*)req->user_data;
    
    // Build JSON response with all routes
    char json[8192] = "{\"routes\":[";
    
    for (size_t i = 0; i < app->route_count; i++) {
        const char *method_str[] = {"GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"};
        char route_json[512];
        
        snprintf(route_json, sizeof(route_json),
                "%s{\"method\":\"%s\",\"path\":\"%s\",\"description\":\"%s\"}",
                i > 0 ? "," : "",
                method_str[app->routes[i].method],
                app->routes[i].path,
                app->routes[i].description ? app->routes[i].description : "");
        
        strcat(json, route_json);
    }
    
    strcat(json, "]}");
    
    crest_response_json(res, json);
}

/* OpenAPI JSON Endpoint Handler */
void crest_openapi_json_handler(crest_request_t *req, crest_response_t *res) {
    crest_app_t *app = (crest_app_t*)req->user_data;
    
    char *openapi_spec = crest_generate_openapi_spec(app);
    if (!openapi_spec) {
        crest_response_status(res, 500);
        crest_response_json(res, "{\"error\":\"Failed to generate OpenAPI specification\"}");
        return;
    }
    
    crest_response_header(res, "Content-Type", "application/json; charset=utf-8");
    crest_response_header(res, "Access-Control-Allow-Origin", "*");
    crest_response_send(res, openapi_spec);
    
    crest_free_openapi_spec(openapi_spec);
}

/* Swagger UI Endpoint Handler */
void crest_swagger_ui_handler(crest_request_t *req, crest_response_t *res) {
    const char *html = "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Swagger UI - Crest API Documentation</title>\n"
        "  <link rel=\"stylesheet\" href=\"https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui.css\" />\n"
        "  <style>\n"
        "    html { box-sizing: border-box; overflow-y: scroll; }\n"
        "    *, *:before, *:after { box-sizing: inherit; }\n"
        "    body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }\n"
        "    .topbar { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 1rem 0; }\n"
        "    .topbar-wrapper { max-width: 1460px; margin: 0 auto; padding: 0 20px; }\n"
        "    .topbar-wrapper h1 { color: white; margin: 0; font-size: 1.5rem; font-weight: 700; }\n"
        "    .topbar-wrapper p { color: rgba(255,255,255,0.9); margin: 0.5rem 0 0 0; font-size: 0.95rem; }\n"
        "    .swagger-ui .topbar { display: none; }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <div class=\"topbar\">\n"
        "    <div class=\"topbar-wrapper\">\n"
        "      <h1>🌊 Crest API - Swagger UI</h1>\n"
        "      <p>Interactive API documentation and testing interface</p>\n"
        "    </div>\n"
        "  </div>\n"
        "  <div id=\"swagger-ui\"></div>\n"
        "  <script src=\"https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-bundle.js\" crossorigin></script>\n"
        "  <script src=\"https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-standalone-preset.js\" crossorigin></script>\n"
        "  <script>\n"
        "    window.onload = function() {\n"
        "      window.ui = SwaggerUIBundle({\n"
        "        url: '/openapi.json',\n"
        "        dom_id: '#swagger-ui',\n"
        "        deepLinking: true,\n"
        "        presets: [\n"
        "          SwaggerUIBundle.presets.apis,\n"
        "          SwaggerUIStandalonePreset\n"
        "        ],\n"
        "        plugins: [\n"
        "          SwaggerUIBundle.plugins.DownloadUrl\n"
        "        ],\n"
        "        layout: 'StandaloneLayout',\n"
        "        defaultModelsExpandDepth: 1,\n"
        "        defaultModelExpandDepth: 1,\n"
        "        docExpansion: 'list',\n"
        "        filter: true,\n"
        "        showExtensions: true,\n"
        "        showCommonExtensions: true,\n"
        "        tryItOutEnabled: true,\n"
        "        requestSnippetsEnabled: true,\n"
        "        persistAuthorization: true,\n"
        "        displayRequestDuration: true,\n"
        "        operationsSorter: 'alpha',\n"
        "        tagsSorter: 'alpha'\n"
        "      });\n"
        "    };\n"
        "  </script>\n"
        "</body>\n"
        "</html>";
    
    crest_response_header(res, "Content-Type", "text/html; charset=utf-8");
    crest_response_header(res, "Cache-Control", "no-cache, no-store, must-revalidate");
    crest_response_send(res, html);
}

/* ReDoc UI Endpoint Handler */
void crest_redoc_ui_handler(crest_request_t *req, crest_response_t *res) {
    const char *html = "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>ReDoc - Crest API Documentation</title>\n"
        "  <style>\n"
        "    body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }\n"
        "    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n"
        "    .header h1 { margin: 0; font-size: 2rem; font-weight: 700; }\n"
        "    .header p { margin: 0.5rem 0 0 0; opacity: 0.95; font-size: 1.1rem; }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <div class=\"header\">\n"
        "    <h1>🌊 Crest API - ReDoc Documentation</h1>\n"
        "    <p>Clean, professional API documentation (read-only)</p>\n"
        "  </div>\n"
        "  <redoc spec-url='/openapi.json'></redoc>\n"
        "  <script src=\"https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js\"></script>\n"
        "</body>\n"
        "</html>";
    
    crest_response_header(res, "Content-Type", "text/html; charset=utf-8");
    crest_response_header(res, "Cache-Control", "no-cache, no-store, must-revalidate");
    crest_response_send(res, html);
}
