site_name: Crest Documentation
site_url: https://muhammad-fiaz.github.io/Crest
site_author: Muhammad Fiaz
site_description: Production-ready RESTful API framework for C and C++

repo_name: muhammad-fiaz/Crest
repo_url: https://github.com/muhammad-fiaz/Crest
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Examples: examples.md
  - API Reference:
    - C API: c_api.md
    - C++ API: cpp_api.md
    - Status Codes: status_codes.md
  - Core Features:
    - Configuration: configuration.md
    - Logging: logging.md
    - Schemas: schemas.md
    - Performance & Concurrency: performance.md
  - Advanced Features:
    - Middleware System: middleware.md
    - WebSocket Support: websocket.md
    - Database Integration: database.md
    - File Upload Handling: file_upload.md
    - Template Engine: templates.md
  - Contributing:
    - Contributing Guide: contributing.md
    - License: license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/muhammad-fiaz
    - icon: fontawesome/solid/envelope
      link: mailto:contact@muhammadfiaz.com
  version:
    provider: mike
