site_name: Crest Documentation
site_url: https://muhammad-fiaz.github.io/crest
site_author: Muhammad Fiaz
site_description: Production-ready RESTful API framework for C and C++

repo_name: muhammad-fiaz/crest
repo_url: https://github.com/muhammad-fiaz/crest
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - API Reference:
    - C API: c_api.md
    - C++ API: cpp_api.md
  - Guides:
    - Configuration: configuration.md
    - Examples: examples.md
  - About:
    - License: license.md
    - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/muhammad-fiaz
    - icon: fontawesome/solid/envelope
      link: mailto:contact@muhammadfiaz.com
  version:
    provider: mike
