-- Crest RESTful API Framework
-- Version: 0.0.0
set_project("crest")
set_version("0.0.0")
set_xmakever("2.8.0")

add_rules("mode.debug", "mode.release")
set_languages("c17", "cxx20")
set_optimize("faster")
set_warnings("all")

if is_plat("windows") then
    add_defines("CREST_WINDOWS", "CREST_EXPORT")
    add_cxxflags("/utf-8")
    add_syslinks("ws2_32", "mswsock")
elseif is_plat("linux") then
    add_defines("CREST_LINUX")
    add_syslinks("pthread")
elseif is_plat("macosx") then
    add_defines("CREST_MACOS")
    add_syslinks("pthread")
end

target("crest")
    set_kind("$(kind)")
    add_files("src/core/*.c")
    add_files("src/core/*.cpp")
    add_files("src/http/*.c")
    add_files("src/router/*.cpp")
    add_files("src/server/*.cpp")
    add_files("src/middleware/*.cpp")
    add_files("src/swagger/*.cpp")
    add_files("src/websocket/*.cpp")
    add_files("src/database/*.cpp")
    add_files("src/upload/*.cpp")
    add_files("src/template/*.cpp")
    add_files("src/utils/*.c")
    add_files("src/utils/*.cpp")
    add_headerfiles("include/(**.h)", "include/(**.hpp)")
    add_includedirs("include", {public = true})
    set_targetdir("build/lib")
    
    if is_kind("shared") then
        add_defines("CREST_BUILD_SHARED")
    end

target("crest_example_cpp")
    set_kind("binary")
    add_files("examples/cpp/main.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_concurrent_example")
    set_kind("binary")
    add_files("examples/cpp/concurrent_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_status_codes_example")
    set_kind("binary")
    add_files("examples/cpp/status_codes_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_schema_example")
    set_kind("binary")
    add_files("examples/cpp/schema_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_middleware_example")
    set_kind("binary")
    add_files("examples/cpp/middleware_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_websocket_example")
    set_kind("binary")
    add_files("examples/cpp/websocket_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_database_example")
    set_kind("binary")
    add_files("examples/cpp/database_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_upload_example")
    set_kind("binary")
    add_files("examples/cpp/upload_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_template_example")
    set_kind("binary")
    add_files("examples/cpp/template_example.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_example_c")
    set_kind("binary")
    add_files("examples/c/*.c")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/bin")

target("crest_tests")
    set_kind("binary")
    add_files("tests/test_basic.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")

target("crest_test_middleware")
    set_kind("binary")
    add_files("tests/test_middleware.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")

target("crest_test_websocket")
    set_kind("binary")
    add_files("tests/test_websocket.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")

target("crest_test_database")
    set_kind("binary")
    add_files("tests/test_database.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")

target("crest_test_upload")
    set_kind("binary")
    add_files("tests/test_upload.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")

target("crest_test_template")
    set_kind("binary")
    add_files("tests/test_template.cpp")
    add_deps("crest")
    add_includedirs("include")
    set_targetdir("build/tests")
