name: remote theme
remote_theme: just-the-docs/just-the-docs

title: Crest Framework
description: A modern, fast, and lightweight REST API framework for C/C++
url: https://muhammad-fiaz.github.io
baseurl: /crest

# Build settings
markdown: kramdown

# Color scheme
color_scheme: dark

# Logo
logo: "/assets/images/crest-logo.png"

# Footer
footer_content: "Copyright &copy; 2025 Muhammad Fiaz. Distributed under the MIT License."

# GitHub
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/muhammad-fiaz/crest"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Navigation
nav_sort: case_insensitive

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links
aux_links:
  "Crest on GitHub":
    - "https://github.com/muhammad-fiaz/crest"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
